"""Pinned model files, verified against what the upstream repository publishes.

Each pin (app/tts_runtime/pins/<name>.json, generated by
scripts/pin_hf_repo.py) names a repository, an exact commit and, for every
file, its size and git object id at that commit. Verification is exact:

  * a small file's git id is sha1("blob <size>\\0" + content);
  * a large (LFS) file's git id is the sha1 of its LFS pointer,
    "version https://git-lfs.github.com/spec/v1\\noid sha256:<hex>\\nsize <n>\\n",
    which embeds the file's sha256 -- so hashing the download and rebuilding
    the pointer proves the sha256 matches upstream's.

This works for gated repositories *without a token*: Hugging Face publishes
the tree (sizes and git ids) openly and masks only the LFS sha256 itself.
Both methods were checked against an ungated repo where the sha256 is shown
(parler-tts-tiny-v1: model.safetensors, spiece.model, config.json all match).

After a file verifies, its sha256 is recorded in a lock (VERIFIED.json)
beside it; workers re-check that sha256 before loading, so a file corrupted
on disk later is caught at load and never used.
"""
from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path

from app.tts_runtime.fsutil import atomic_write_bytes, sha256_file

PINS_DIR = Path(__file__).resolve().parent / "pins"
LOCK_NAME = "VERIFIED.json"


class HashMismatch(RuntimeError):
    pass


@dataclass(frozen=True)
class FilePin:
    path: str
    size: int
    git_oid: str
    lfs: bool


@dataclass(frozen=True)
class RepoPin:
    name: str            # pin name, e.g. "indic_parler"
    repo: str
    revision: str
    files: tuple[FilePin, ...]
    license: str
    gated: bool
    base_url: str | None = None      # tests serve pins from a local server

    def url(self, f: FilePin) -> str:
        if self.base_url:
            return f"{self.base_url.rstrip('/')}/{f.path}"
        return f"https://huggingface.co/{self.repo}/resolve/{self.revision}/{f.path}"

    def total_bytes(self) -> int:
        return sum(f.size for f in self.files)


def load_pin(name: str, pins_dir: Path = PINS_DIR) -> RepoPin:
    d = json.loads((pins_dir / f"{name}.json").read_text(encoding="utf-8"))
    return RepoPin(d["name"], d["repo"], d["revision"],
                   tuple(FilePin(f["path"], int(f["size"]), f["git_oid"], bool(f["lfs"])) for f in d["files"]),
                   d["license"], bool(d.get("gated", False)), d.get("base_url"))


def git_blob_sha1_of(data: bytes) -> str:
    return hashlib.sha1(b"blob %d\x00" % len(data) + data).hexdigest()


def lfs_pointer(sha256_hex: str, size: int) -> bytes:
    return f"version https://git-lfs.github.com/spec/v1\noid sha256:{sha256_hex}\nsize {size}\n".encode()


def verify_file(path: str | Path, pin: FilePin) -> str:
    """sha256 of `path` if it is exactly the pinned file, else HashMismatch."""
    p = Path(path)
    size = p.stat().st_size
    if size != pin.size:
        raise HashMismatch(f"{pin.path}: size {size} != pinned {pin.size}")
    sha = hashlib.sha256()
    blob = hashlib.sha1(b"blob %d\x00" % size)
    with open(p, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            sha.update(chunk)
            if not pin.lfs:
                blob.update(chunk)
    digest = sha.hexdigest()
    got = git_blob_sha1_of(lfs_pointer(digest, size)) if pin.lfs else blob.hexdigest()
    if got != pin.git_oid:
        raise HashMismatch(f"{pin.path}: content does not match upstream (git id {got[:12]} != pinned "
                           f"{pin.git_oid[:12]}); refusing to use it")
    return digest


def model_dir(home: Path, pin: RepoPin) -> Path:
    return home / "models" / pin.name / pin.revision


def read_lock(folder: Path) -> dict:
    try:
        return json.loads((folder / LOCK_NAME).read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError):
        return {}


def write_lock(folder: Path, pin: RepoPin, sha256s: dict[str, str]) -> None:
    atomic_write_bytes(folder / LOCK_NAME, json.dumps(
        {"repo": pin.repo, "revision": pin.revision, "sha256": sha256s}, indent=1).encode())


def provisioned(home: Path, pin: RepoPin) -> tuple[bool, str]:
    """Every pinned file present and recorded as verified (cheap: no hashing)."""
    folder = model_dir(home, pin)
    lock = read_lock(folder).get("sha256", {})
    missing = [f.path for f in pin.files if f.path not in lock or not (folder / f.path).exists()]
    if missing:
        return False, f"{len(missing)} of {len(pin.files)} file(s) not provisioned, e.g. {missing[0]}"
    return True, ""


def verify_locked(folder: Path, pin: RepoPin) -> None:
    """Re-hash every file against the lock before loading. ModelCorrupt on mismatch."""
    from app.tts_runtime.adapters.base import ModelCorrupt

    lock = read_lock(folder).get("sha256", {})
    for f in pin.files:
        p = folder / f.path
        if f.path not in lock or not p.exists():
            raise ModelCorrupt(str(p), "missing or never verified")
        got = sha256_file(p)
        if got != lock[f.path]:
            raise ModelCorrupt(str(p), f"sha256 {got[:12]} != verified {lock[f.path][:12]} -- corrupted on disk")
